网页上以约1秒的间隔从10到0进行倒计时
Chrome、腾讯浏览器、360极速浏览器可以单个刷出数字、控制台循环，然后程序会抛异常，再控制台单独循环一次数字。
java.net.SocketException: Software caused connection abort: socket write error
Firefox倒计时后一下显示。